"""
setup/capability_seeds.py — Seed phrases for all 7 capability primitives.

These phrases are embedded and clustered (K-means, K=3) to build the
multi-prototype centroids used in capability projection.

Guidelines per capability:
  - 60–80 seeds minimum
  - Cover: verb phrases, noun phrases, domain variants (tech/research/business)
  - Include edge cases and slightly ambiguous ones (they help calibrate)
  - DO NOT include seeds that belong to another capability
"""

from core.models import Capability

CAPABILITY_SEEDS: dict[str, list[str]] = {

    # ────────────────────────────────────────────────────────────────────
    Capability.GATHER.value: [
        # Core search / lookup (pure retrieval verbs)
        "find information about",
        "look up",
        "search for",
        "collect data on",
        "gather resources",
        "find examples of",
        "retrieve relevant information",
        "scan for",
        "browse for",
        "fetch the data",
        "locate",
        "find out about",
        "look into",
        "learn what is available",
        "discover what exists",
        "explore what is out there",
        # Academic — finding, not reading/understanding
        "find papers on",
        "search academic literature",
        "identify relevant studies",
        "find citations for",
        "collect references",
        "find prior art",
        "search for existing work on",
        "locate published research about",
        "find related publications",
        "get the bibliography for",
        # Data collection — mechanical retrieval
        "collect the dataset",
        "pull the data",
        "scrape the data",
        "acquire the data",
        "download the dataset",
        "extract data from",
        "gather metrics",
        "collect measurements",
        "retrieve records",
        "fetch logs",
        "pull statistics",
        "ingest the raw data",
        "import the CSV",
        "load the data from disk",
        "read in the data file",
        "copy the data over",
        "query the database for the records",
        "fetch the API response",
        "pull the repository",
        "access the remote resource",
        "get the records from storage",
        "retrieve the stored entries",
        "grab the latest version",
        "obtain the raw data",
        "export the data for use",
        "read in the logs",
        # Requirements / business — collecting not interpreting
        "gather requirements",
        "collect stakeholder input",
        "elicit requirements",
        "collect feedback from users",
        "gather constraints",
        "find what is needed",
        "get the list of requirements",
        "collect the user stories",
        "record stakeholder responses",
        # Technical — locating not evaluating
        "find the API documentation",
        "look up the spec",
        "find the error message",
        "search the codebase for",
        "locate the relevant files",
        "find the configuration file",
        "find available tools",
        "look up how to do this",
        "find the relevant library",
        "get the list of available endpoints",
        # Creative — sourcing not evaluating
        "gather inspiration",
        "collect examples",
        "find reference images",
        "look for templates",
        "find similar work",
        "collect sample outputs",
        "source reference material",
    ],

    # ────────────────────────────────────────────────────────────────────
    Capability.ANALYZE.value: [
        # Core analysis
        "understand deeply",
        "analyze",
        "synthesize",
        "explain how",
        "break down",
        "examine",
        "study in depth",
        "comprehend",
        "make sense of",
        "figure out how",
        "understand the mechanism",
        "think through",
        "work through",
        "reason about",
        # Pattern finding
        "find patterns in",
        "identify trends",
        "extract insights from",
        "spot the key themes",
        "identify the main concepts",
        "find the root cause",
        "determine why",
        "uncover the relationships",
        "map out the connections",
        "understand the structure",
        # Comparison
        "compare approaches",
        "evaluate options",
        "contrast methods",
        "weigh the trade-offs",
        "assess the differences",
        "benchmark against",
        "analyse the pros and cons",
        # Deep understanding
        "deeply understand",
        "thoroughly grasp",
        "get to the bottom of",
        "understand the fundamentals",
        "internalize the concepts",
        "understand the theory behind",
        "understand the math behind",
        "understand the principles",
        # Distil — cognitive extraction, not output writing
        "distil the key points",
        "extract the main ideas",
        "identify what matters",
        "find the important parts",
        # Research analysis
        "analyse the results",
        "interpret the data",
        "draw conclusions from",
        "make inferences from",
        "understand the implications",
        "critically evaluate",
        "assess the evidence",
        # Understand / reasoning — NOT output/communication
        "understand why this happens",
        "figure out the underlying cause",
        "comprehend the causal mechanism",
        "reason about the root cause",
        "infer what is really going on",
    ],

    # ────────────────────────────────────────────────────────────────────
    Capability.PLAN.value: [
        # Core planning
        "design",
        "structure",
        "architect",
        "outline",
        "plan",
        "organise",
        "strategize",
        "map out",
        "define the approach",
        "lay out the steps",
        "determine how to",
        "figure out the approach",
        "decide on the method",
        "choose the strategy",
        # Software design
        "design the system",
        "architect the solution",
        "design the database schema",
        "plan the API",
        "structure the codebase",
        "define the interfaces",
        "design the data model",
        "plan the architecture",
        "design the modules",
        "plan the components",
        "sketch the solution",
        "define the structure",
        # Project planning
        "break into tasks",
        "define milestones",
        "create a roadmap",
        "outline the phases",
        "identify what needs to be done",
        "sequence the work",
        "prioritise the tasks",
        "schedule the work",
        "define the scope",
        # Decision making
        "decide what to build",
        "choose the best approach",
        "pick the right technology",
        "decide how to structure",
        "define the requirements",
        "decide on the design",
        "figure out the solution",
        # Research planning
        "design the experiment",
        "plan the methodology",
        "define the research questions",
        "structure the argument",
        "outline the paper",
        "plan the study",
        # Creative planning
        "plan the structure",
        "outline the story",
        "plan the layout",
        "define the narrative arc",
    ],

    # ────────────────────────────────────────────────────────────────────
    Capability.EXECUTE.value: [
        # Core building
        "build",
        "implement",
        "write code",
        "create",
        "develop",
        "make",
        "construct",
        "program",
        "code up",
        "produce",
        "generate",
        "craft",
        # Software development
        "write the function",
        "implement the algorithm",
        "code the feature",
        "build the module",
        "create the class",
        "write the script",
        "build the API",
        "develop the application",
        "implement the logic",
        "write the tests",
        "create the database",
        "build the UI",
        "implement the interface",
        "write the configuration",
        "create the pipeline",
        "build the model",
        "train the model",
        "deploy the service",
        # Writing / content creation
        "write the document",
        "draft the report",
        "write the essay",
        "compose the email",
        "author the content",
        "write the code",
        "produce the output",
        "generate the content",
        # Data work
        "process the data",
        "transform the data",
        "run the analysis",
        "compute the results",
        "calculate",
        "run the query",
        "execute the computation",
        # Creative execution
        "design the graphic",
        "produce the prototype",
        "create the mockup",
        "build the demo",
        "create the proof of concept",
        # General doing
        "do it",
        "carry out",
        "perform the task",
        "complete the work",
        "put it together",
        "produce the deliverable",
    ],

    # ────────────────────────────────────────────────────────────────────
    Capability.VERIFY.value: [
        # Core testing
        "test",
        "validate",
        "check",
        "verify",
        "benchmark",
        "evaluate",
        "assess",
        "confirm",
        "review output",
        # Software testing
        "run the tests",
        "write unit tests",
        "test the implementation",
        "check for bugs",
        "debug",
        "find the errors",
        "check edge cases",
        "test the edge cases",
        "run the test suite",
        "check the output",
        "verify correctness",
        "validate the results",
        "check the logic",
        "test the API",
        "test the function",
        "check for regressions",
        "test on different inputs",
        # Quality assurance
        "ensure quality",
        "quality check",
        "review for errors",
        "proofread",
        "check for mistakes",
        "ensure correctness",
        "sanity check",
        "cross-check",
        # Performance
        "benchmark the performance",
        "measure the latency",
        "profile the code",
        "check the speed",
        "test scalability",
        "measure accuracy",
        # Research verification
        "verify the findings",
        "validate the hypothesis",
        "fact-check",
        "check the data quality",
        "validate the model",
        "test the approach",
        "check if it works",
        # Compliance
        "check compliance",
        "verify requirements are met",
        "confirm it meets the spec",
        "validate against criteria",
        "check the constraints are satisfied",
    ],

    # ────────────────────────────────────────────────────────────────────
    Capability.REFINE.value: [
        # Core improvement
        "improve",
        "optimize",
        "fix",
        "refine",
        "iterate",
        "enhance",
        "clean up",
        "polish",
        # Software improvement
        "refactor",
        "optimise the code",
        "improve performance",
        "reduce complexity",
        "simplify",
        "remove duplication",
        "improve readability",
        "fix the bug",
        "address the issue",
        "resolve the problem",
        "tune the parameters",
        "improve the algorithm",
        "optimise for speed",
        "reduce memory usage",
        "improve the accuracy",
        # Iterative improvement
        "iterate on",
        "revise",
        "update based on feedback",
        "improve based on testing",
        "address the issues found",
        "fix what was wrong",
        "go back and improve",
        "second pass",
        "make it better",
        # Writing refinement
        "edit",
        "revise the draft",
        "improve the writing",
        "clarify the explanation",
        "tighten the argument",
        "rework the structure",
        "improve the flow",
        # Research refinement
        "re-run with improvements",
        "tune the model",
        "improve the approach",
        "address the limitations",
        "refine the methodology",
    ],

    # ────────────────────────────────────────────────────────────────────
    Capability.COMMUNICATE.value: [
        # Core communication
        "document",
        "present",
        "explain results",
        "report",
        "summarize output",
        "write up",
        "publish",
        "share",
        # Technical documentation
        "write the documentation",
        "create the README",
        "document the API",
        "write the user guide",
        "create the specification",
        "write the changelog",
        "document the architecture",
        "write comments in the code",
        "create documentation",
        # Presentation
        "create the presentation",
        "prepare the slides",
        "present the findings",
        "explain to stakeholders",
        "communicate the results",
        "present the analysis",
        # Summary
        "summarize for the user",
        "explain what was found",
        "write the summary",
        "create the report",
        "produce the final output",
        "package the results",
        "explain the outcome",
        # Writing for audience
        "write for a non-technical audience",
        "explain in simple terms",
        "translate the findings",
        "create the brief",
        "write the executive summary",
        "prepare the handover",
        # Output formatting
        "format the output",
        "structure the response",
        "present clearly",
        "make it readable",
        "organise the information",
    ],
}


# ── Contrastive seeds (NOT included in centroid mean — used for validation only) ─
#
# Purpose: push capability centroids apart during the repulsion step.
# Design principle: seeds are HEAVILY WEIGHTED toward each capability's actual
# closest confusables (from the pairwise similarity table), so that neg_mean
# points firmly into the confusable direction and repulsion is maximally effective.
#
# Observed worst pairs → seeding strategy per capability:
#   GATHER     → weight toward ANALYZE, VERIFY, COMMUNICATE
#   ANALYZE    → weight toward COMMUNICATE, VERIFY, PLAN
#   PLAN       → weight toward COMMUNICATE, ANALYZE, EXECUTE
#   EXECUTE    → weight toward ANALYZE, PLAN, COMMUNICATE
#   VERIFY     → weight toward ANALYZE, COMMUNICATE, REFINE
#   REFINE     → weight toward ANALYZE, VERIFY, EXECUTE
#   COMMUNICATE → weight toward ANALYZE, PLAN, VERIFY
#
CAPABILITY_CONTRASTIVE_SEEDS: dict[str, dict[str, list[str]]] = {

    # ── GATHER ───────────────────────────────────────────────────────────
    # Most confusable with: ANALYZE (0.72), COMMUNICATE (0.71), VERIFY (0.70)
    Capability.GATHER.value: {
        "not_gather": [
            # ── ANALYZE ×15 ──────────────────────────────────────────────
            "reason through the implications of the data",
            "draw conclusions from the evidence",
            "synthesize the findings across sources",
            "interpret what the results mean",
            "identify the root cause from the data",
            "think through how the pieces connect",
            "evaluate the significance of the findings",
            "make inferences from the available evidence",
            "understand the underlying mechanism",
            "critically assess the evidence",
            "work through the logic of the outcome",
            "comprehend what the patterns are telling us",
            "weigh the evidence and reach a conclusion",
            "determine why this pattern exists",
            "form a judgment based on the information",
            # ── COMMUNICATE ×12 ──────────────────────────────────────────
            "write the final report",
            "present the findings to stakeholders",
            "create the documentation",
            "explain the results in simple terms",
            "write the executive summary",
            "prepare the slides for the meeting",
            "communicate the outcome to the team",
            "publish the results",
            "produce the written deliverable",
            "draft the technical write-up",
            "describe what was found to a non-technical audience",
            "write up the conclusions",
            # ── VERIFY ×10 ───────────────────────────────────────────────
            "run the test suite to check correctness",
            "validate that the output is accurate",
            "fact-check the claims",
            "benchmark the performance",
            "assert the results are correct",
            "confirm it meets the specification",
            "check for regressions",
            "sanity-check the numbers",
            "test the function with edge cases",
            "verify the implementation is working",
            # ── PLAN ×4 ──────────────────────────────────────────────────
            "design the research methodology",
            "plan the investigation approach",
            "outline the solution strategy",
            "decide how to structure the work",
            # ── EXECUTE ×4 ───────────────────────────────────────────────
            "implement the data collection pipeline",
            "build the scraper",
            "write the ingestion script",
            "develop the solution",
            # ── REFINE ×3 ────────────────────────────────────────────────
            "clean the raw dataset",
            "deduplicate the collected entries",
            "filter out irrelevant results",
        ]
    },

    # ── ANALYZE ──────────────────────────────────────────────────────────
    # Most confusable with: COMMUNICATE (0.748), VERIFY (0.745), PLAN (0.719)
    Capability.ANALYZE.value: {
        "not_analyze": [
            # ── COMMUNICATE ×23 ──────────────────────────────────────────
            "write the final report",
            "present the findings to stakeholders",
            "create the documentation",
            "explain the results in simple terms",
            "write the executive summary",
            "prepare the presentation slides",
            "write the user guide",
            "communicate the outcome to the team",
            "publish the results",
            "produce the written deliverable",
            "draft the technical specification",
            "format the report for distribution",
            "write up the conclusions for the audience",
            "describe the solution to non-technical users",
            "share the summary with the stakeholders",
            # extra COMMUNICATE seeds to push ANALYZE away from COMMUNICATE space
            "explain the outcome to the client",
            "write a clear description of what was found",
            "summarize the results for stakeholders",
            "produce the handover document",
            "communicate the findings in plain language",
            "write the technical write-up",
            "present clearly to the audience",
            "document and share the conclusions",
            # ── VERIFY ×23 ───────────────────────────────────────────────
            "run the test suite",
            "validate the output is correct",
            "check for bugs",
            "benchmark the performance",
            "assert the results are accurate",
            "verify the implementation is working",
            "check edge cases",
            "confirm it meets the requirements",
            "test the function with different inputs",
            "check for regressions",
            "validate against the spec",
            "run quality assurance on the output",
            "detect errors in the implementation",
            "test whether the solution is correct",
            "confirm the model produces valid results",
            # extra VERIFY seeds to push ANALYZE away from VERIFY space
            "run the unit tests and check pass rate",
            "assert the function returns the right value",
            "measure the test coverage",
            "test the implementation end-to-end",
            "confirm the output matches the expected value",
            "run the validation suite",
            "execute the test cases",
            "check for correctness with automated tests",
            # ── PLAN ×12 ─────────────────────────────────────────────────
            "design the architecture",
            "outline the implementation approach",
            "plan the solution structure",
            "define the strategy",
            "decide how to structure the codebase",
            "map out the steps needed",
            "choose the right technology stack",
            "architect the solution",
            "define the project roadmap",
            "lay out the phases of work",
            "determine the approach before building",
            "sketch the high-level design",
            # ── GATHER ×6 ────────────────────────────────────────────────
            "collect the dataset",
            "search for relevant papers",
            "retrieve the logs",
            "download the raw data",
            "fetch the records from the database",
            "scrape the website for information",
            # ── EXECUTE ×4 ───────────────────────────────────────────────
            "implement the algorithm",
            "build the feature",
            "write the code",
            "develop the solution",
            # ── REFINE ×4 ────────────────────────────────────────────────
            "refactor the code",
            "optimise the performance",
            "fix the bug",
            "improve the implementation",
        ]
    },

    # ── PLAN ─────────────────────────────────────────────────────────────
    # Most confusable with: COMMUNICATE (0.733), ANALYZE (0.719), EXECUTE (0.673)
    Capability.PLAN.value: {
        "not_plan": [
            # ── COMMUNICATE ×15 ──────────────────────────────────────────
            "write the final report",
            "present the findings to stakeholders",
            "create the documentation",
            "explain the results in plain language",
            "write the executive summary",
            "prepare the slides",
            "write the user guide",
            "communicate the outcome to the team",
            "publish the conclusions",
            "produce the written deliverable",
            "format and share the output",
            "draft the technical specification",
            "write up the design decisions for the audience",
            "describe the system to non-technical users",
            "document what was built and why",
            # ── ANALYZE ×15 ──────────────────────────────────────────────
            "reason through the implications",
            "draw conclusions from the evidence",
            "synthesize the research findings",
            "interpret what the data means",
            "identify the root cause",
            "understand the underlying mechanism",
            "evaluate the trade-offs",
            "critically assess the evidence",
            "make sense of the patterns",
            "figure out why this is happening",
            "think through the logic",
            "weigh the pros and cons",
            "determine the significance of the findings",
            "comprehend the theoretical basis",
            "distil insights from the information",
            # ── EXECUTE ×10 ──────────────────────────────────────────────
            "implement the algorithm",
            "build the feature",
            "write the code",
            "develop the solution",
            "construct the system",
            "program the logic",
            "produce the output",
            "create the module",
            "run the computation",
            "generate the artifact",
            # ── GATHER ×4 ────────────────────────────────────────────────
            "collect the requirements",
            "look up best practices",
            "find what frameworks are available",
            "retrieve the specification",
            # ── VERIFY ×4 ────────────────────────────────────────────────
            "validate the design against requirements",
            "check that the plan is feasible",
            "confirm the approach will work",
            "test the prototype",
            # ── REFINE ×3 ────────────────────────────────────────────────
            "revise the plan based on feedback",
            "iterate on the design",
            "update the roadmap",
        ]
    },

    # ── EXECUTE ──────────────────────────────────────────────────────────
    # Most confusable with: ANALYZE (0.682), PLAN (0.673), COMMUNICATE (0.618)
    Capability.EXECUTE.value: {
        "not_execute": [
            # ── ANALYZE ×12 ──────────────────────────────────────────────
            "reason through the implications",
            "draw conclusions from the evidence",
            "synthesize the research findings",
            "interpret what the data means",
            "identify the root cause",
            "understand the underlying mechanism",
            "evaluate the trade-offs",
            "critically assess the evidence",
            "figure out why this is happening",
            "think through the logic",
            "weigh the pros and cons",
            "comprehend the theoretical basis",
            # ── PLAN ×12 ─────────────────────────────────────────────────
            "design the architecture",
            "outline the implementation approach",
            "plan the solution structure",
            "define the strategy",
            "decide how to structure the codebase",
            "map out the steps needed",
            "choose the right technology stack",
            "architect the solution",
            "define the project roadmap",
            "lay out the phases of work",
            "sketch the high-level design",
            "define the interface contracts",
            # ── COMMUNICATE ×8 ───────────────────────────────────────────
            "write the final report",
            "present the findings to stakeholders",
            "create the documentation",
            "explain the results in simple terms",
            "write the executive summary",
            "document what was built and how it works",
            "write the README",
            "explain to stakeholders",
            # ── REFINE ×7 ────────────────────────────────────────────────
            "refactor the existing code",
            "optimise the function",
            "fix the bug",
            "clean up the code",
            "improve the performance",
            "address the issues found in review",
            "iterate on the draft",
            # ── GATHER ×4 ────────────────────────────────────────────────
            "look up the API documentation",
            "find relevant code examples",
            "retrieve the specification",
            "search the codebase for",
            # ── VERIFY ×4 ────────────────────────────────────────────────
            "run the tests",
            "check that the implementation is correct",
            "validate the output",
            "benchmark performance",
        ]
    },

    # ── VERIFY ───────────────────────────────────────────────────────────
    # Most confusable with: ANALYZE (0.745), COMMUNICATE (0.716), REFINE (0.629)
    Capability.VERIFY.value: {
        "not_verify": [
            # ── ANALYZE ×23 ──────────────────────────────────────────────
            "reason through the implications of the results",
            "draw conclusions from the test output",
            "synthesize what the benchmarks are showing",
            "interpret why the performance is this way",
            "identify the root cause of the failures",
            "understand the underlying mechanism of the error",
            "evaluate the significance of the test results",
            "make inferences from the benchmark data",
            "think through what the error patterns mean",
            "comprehend the performance characteristics",
            "weigh the evidence from multiple test runs",
            "determine why the failures are occurring",
            "figure out what the results imply",
            "distil insights from the evaluation output",
            "critically assess the overall quality evidence",
            # extra ANALYZE seeds to push VERIFY away from ANALYZE space
            "reason deductively from the evidence to a conclusion",
            "form a hypothesis about what is causing the issue",
            "understand the theoretical basis of the problem",
            "synthesize competing explanations for the behaviour",
            "evaluate the causal mechanism behind the pattern",
            "think through the logical implications of the data",
            "make sense of the deeper meaning in the results",
            "comprehend the structural relationships in the output",
            # ── COMMUNICATE ×15 ──────────────────────────────────────────
            "write the final report",
            "present the findings to stakeholders",
            "create the test documentation",
            "explain the results in simple terms",
            "write the quality summary for the team",
            "prepare the release notes",
            "write the user guide",
            "communicate the outcome",
            "publish the results",
            "document what was tested and why",
            "produce the written test report",
            "draft the quality assurance write-up",
            "write up the conclusions for the audience",
            "describe the findings to non-technical users",
            "share the summary with stakeholders",
            # ── REFINE ×8 ────────────────────────────────────────────────
            "fix the bug that was found",
            "improve the code after testing",
            "address the test failures",
            "clean up what the review flagged",
            "optimise after profiling",
            "iterate to fix the edge cases",
            "refactor based on test results",
            "improve accuracy after evaluation",
            # ── GATHER ×4 ────────────────────────────────────────────────
            "collect test cases from the spec",
            "find existing test suites",
            "look up known edge cases",
            "retrieve the reference outputs",
            # ── PLAN ×4 ──────────────────────────────────────────────────
            "plan the testing strategy",
            "design the test cases",
            "outline the QA approach",
            "decide what to test",
            # ── EXECUTE ×4 ───────────────────────────────────────────────
            "write the unit tests",
            "implement the test harness",
            "build the benchmarking suite",
            "create the test data",
        ]
    },

    # ── REFINE ───────────────────────────────────────────────────────────
    # Most confusable with: ANALYZE (0.680), VERIFY (0.629), EXECUTE (0.568)
    Capability.REFINE.value: {
        "not_refine": [
            # ── ANALYZE ×15 ──────────────────────────────────────────────
            "reason through the implications",
            "draw conclusions from the evidence",
            "synthesize the research findings",
            "interpret what the data means",
            "identify the root cause before fixing",
            "understand the underlying mechanism of the problem",
            "evaluate the performance characteristics",
            "critically assess the evidence",
            "think through why the issue occurs",
            "comprehend the theoretical basis of the problem",
            "weigh the evidence to determine the cause",
            "determine why the performance is degraded",
            "figure out what is causing the bug",
            "distil insights from the profiling data",
            "make sense of the error patterns",
            # ── VERIFY ×12 ───────────────────────────────────────────────
            "run the test suite to find issues",
            "validate that the output is correct",
            "check for correctness",
            "benchmark to see if it is fast enough",
            "confirm it meets the spec",
            "assert correctness with automated tests",
            "check for regressions",
            "test the edge cases",
            "verify the implementation is working",
            "validate against the requirements",
            "run quality checks",
            "measure the accuracy of the output",
            # ── EXECUTE ×8 ───────────────────────────────────────────────
            "implement the feature from scratch",
            "build the new module",
            "write the initial version",
            "create the first draft",
            "develop the solution",
            "produce the output",
            "write the code",
            "generate the artifact",
            # ── PLAN ×4 ──────────────────────────────────────────────────
            "design the refactoring strategy",
            "plan which improvements to make",
            "outline the optimisation approach",
            "decide what to fix first",
            # ── GATHER ×3 ────────────────────────────────────────────────
            "look up how to optimise this pattern",
            "find examples of cleaner implementations",
            "research best practices for refactoring",
            # ── COMMUNICATE ×3 ───────────────────────────────────────────
            "document the changes made",
            "explain what was improved and why",
            "write up the optimisation results",
        ]
    },

    # ── COMMUNICATE ──────────────────────────────────────────────────────
    # Most confusable with: ANALYZE (0.748), PLAN (0.733), VERIFY (0.716)
    Capability.COMMUNICATE.value: {
        "not_communicate": [
            # ── ANALYZE ×15 ──────────────────────────────────────────────
            "reason through the implications of the results",
            "draw conclusions from the evidence",
            "synthesize the research findings",
            "interpret what the data means",
            "identify the root cause of the problem",
            "understand the underlying mechanism",
            "evaluate the trade-offs between options",
            "critically assess the evidence",
            "make sense of the patterns in the data",
            "figure out why this is happening",
            "think through the logic",
            "weigh the pros and cons",
            "determine the significance of the findings",
            "comprehend the theoretical basis",
            "distil insights from the information",
            # ── PLAN ×12 ─────────────────────────────────────────────────
            "design the architecture",
            "outline the implementation approach",
            "plan the solution structure",
            "define the strategy",
            "decide how to structure the codebase",
            "map out the steps needed",
            "choose the right technology stack",
            "architect the solution",
            "define the project roadmap",
            "lay out the phases of work",
            "sketch the high-level design",
            "define the interface contracts",
            # ── VERIFY ×12 ───────────────────────────────────────────────
            "run the test suite",
            "validate the output is correct",
            "check for bugs",
            "benchmark the performance",
            "assert the results are accurate",
            "verify the implementation is working",
            "check edge cases",
            "confirm it meets the requirements",
            "test the function with different inputs",
            "check for regressions",
            "validate against the spec",
            "detect errors in the implementation",
            # ── EXECUTE ×5 ───────────────────────────────────────────────
            "implement the feature",
            "build the thing",
            "write the code",
            "generate the output artifact",
            "develop the solution",
            # ── GATHER ×4 ────────────────────────────────────────────────
            "collect the data before writing",
            "look up facts to support the document",
            "retrieve the information",
            "search for the relevant material",
            # ── REFINE ×3 ────────────────────────────────────────────────
            "edit the draft for clarity",
            "revise the document based on feedback",
            "improve the writing quality",
        ]
    },
}
